### ISSUE TITLE
Size of "IPFS website" is far off?

### ISSUE THREAD

**Issue by sinkuu** [ipfs-cluster/collab.ipfscluster.io#13]
IPFS Website cluster's Size is said to be 600MB on collab.ipfscluster.io., but when I tried setting up a follower, the repo size gained by at least 38GB.

**Comment by hsanjuan** [comment]
Hello,

I have heard reports that this cluster is incorrectly fetching some filecoin params that were pinned in the past, even though they are now unpinned. This is possibly a bug in cluster.

Until I can figure it out/fix, the workaround is:

1) Start `ipfs-cluster-follow` and let it sync to the current head (no more "new head" messages).
2) Stop `ipfs-cluster-follow`
3) Start `ipfs-cluster-follow` again.

That should cancel the large pin and it should not retrigger it again on the second start. You can run `ipfs repo gc` to clean up your repo from all the non-pinned stuff.

**Comment by sinkuu** [comment]
I see, thank you for the explanation.

**Comment by hsanjuan** [comment]
Would you be able to build and test with the latest ipfs-cluster-follow from master @sinkuu ? (https://github.com/ipfs/ipfs-cluster).

**Comment by sinkuu** [comment]
@hsanjuan Great, it seems to be working correctly - `ipfs-cluster-follow ipfs-websites run` stops after retrieving about ~~700~~600 MB of data.
Now it logs `WARN    crdt    go-ds-crdt@v0.1.11/crdt.go:364  backwards compatibility: parsing head as CID.%!(EXTRA <nil>)` repeatedly, is that expected?

**Comment by hsanjuan** [comment]
Awesome!

Yes, this is expected because the leader runs the previous version, but I will silence (and fix) this warning. For the moment you  can safely ignore.
