### ISSUE TITLE
Hosting a collaborative cluster

### ISSUE THREAD

**Issue by shapnam83** [ipfs-cluster/collab.ipfscluster.io#8]
I am trying to host a collaborative cluster with follower nodes following a domain name. The commands for the follower node is clearly given. I need some help in hosting the collaborative cluster based on a webpage. Basically, the setup involves a webpage receiving updates frequently and the follower nodes in the cluster need to pin the updates regularly in the local storage.
It will be helpful to know how to host a collaborative cluster for this scenario.

**Comment by hsanjuan** [comment]
Hello, there is documentation here: https://cluster.ipfs.io/documentation/collaborative/

This issue is not related to this website, for additional support go to https://discuss.ipfs.io.
